-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: library_entries; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.library_entries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    type text DEFAULT 'algorithm'::text NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    share_token uuid DEFAULT gen_random_uuid() NOT NULL,
    CONSTRAINT library_entries_type_check CHECK ((type = ANY (ARRAY['algorithm'::text, 'pattern'::text, 'data-structure'::text, 'concept'::text, 'technique'::text, 'cheatsheet'::text, 'note'::text])))
);

ALTER TABLE public.library_entries OWNER TO postgres;

-- Name: library_entries library_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.library_entries
    ADD CONSTRAINT library_entries_pkey PRIMARY KEY (id);

-- Name: library_entries_share_token; Type: INDEX; Schema: public; Owner: postgres

CREATE UNIQUE INDEX library_entries_share_token ON public.library_entries USING btree (share_token);

-- Name: library_entries_user_id_updated_at; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX library_entries_user_id_updated_at ON public.library_entries USING btree (user_id, updated_at DESC);

-- Name: library_entries library_entries_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.library_entries
    ADD CONSTRAINT library_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- Name: library_entries; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.library_entries ENABLE ROW LEVEL SECURITY;

-- Name: library_entries library_entries_delete_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY library_entries_delete_own ON public.library_entries FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: library_entries library_entries_insert_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY library_entries_insert_own ON public.library_entries FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

-- Name: library_entries library_entries_select_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY library_entries_select_own ON public.library_entries FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));

-- Name: library_entries library_entries_update_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY library_entries_update_own ON public.library_entries FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));

-- Name: TABLE library_entries; Type: ACL; Schema: public; Owner: postgres

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.library_entries TO anon;
GRANT ALL ON TABLE public.library_entries TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.library_entries TO service_role;

