-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: questions; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.questions (
    id text NOT NULL,
    topic text NOT NULL,
    file text NOT NULL,
    number integer NOT NULL,
    title text NOT NULL,
    body_html text NOT NULL,
    label text NOT NULL,
    group_slug text NOT NULL,
    created_by uuid,
    markdown text,
    lang text,
    tags text,
    problem text,
    starred boolean DEFAULT false NOT NULL,
    priority text,
    grey_zone boolean DEFAULT false NOT NULL,
    code text,
    output text,
    problem_html text,
    prerequisites text,
    CONSTRAINT questions_priority_check CHECK ((priority = ANY (ARRAY['high'::text, 'med'::text, 'low'::text])))
);

ALTER TABLE public.questions OWNER TO postgres;

-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);

-- Name: questions_created_by; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX questions_created_by ON public.questions USING btree (created_by);

-- Name: questions_created_by_grey_zone; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX questions_created_by_grey_zone ON public.questions USING btree (created_by) WHERE grey_zone;

-- Name: questions_created_by_priority; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX questions_created_by_priority ON public.questions USING btree (created_by) WHERE (priority IS NOT NULL);

-- Name: questions_created_by_starred; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX questions_created_by_starred ON public.questions USING btree (created_by) WHERE starred;

-- Name: questions_topic_file; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX questions_topic_file ON public.questions USING btree (topic, file);

-- Name: questions questions_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;

-- Name: questions; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- Name: questions questions_delete_admin; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY questions_delete_admin ON public.questions FOR DELETE TO authenticated USING (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false));

-- Name: questions questions_delete_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY questions_delete_own ON public.questions FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = created_by));

-- Name: questions questions_insert_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY questions_insert_own ON public.questions FOR INSERT TO authenticated WITH CHECK (((( SELECT auth.uid() AS uid) = created_by) AND (COALESCE(((( SELECT auth.jwt() AS jwt) ->> 'is_anonymous'::text))::boolean, false) = false)));

-- Name: questions questions_select_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY questions_select_own ON public.questions FOR SELECT TO authenticated USING ((created_by = ( SELECT auth.uid() AS uid)));

-- Name: questions questions_update_admin; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY questions_update_admin ON public.questions FOR UPDATE TO authenticated USING (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false)) WITH CHECK (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false));

-- Name: questions questions_update_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY questions_update_own ON public.questions FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = created_by)) WITH CHECK (((( SELECT auth.uid() AS uid) = created_by) AND (COALESCE(((( SELECT auth.jwt() AS jwt) ->> 'is_anonymous'::text))::boolean, false) = false)));

-- Name: TABLE questions; Type: ACL; Schema: public; Owner: postgres

GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.questions TO anon;
GRANT ALL ON TABLE public.questions TO authenticated;
GRANT ALL ON TABLE public.questions TO service_role;

