-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: sections; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.sections (
    topic text NOT NULL,
    file text NOT NULL,
    label text NOT NULL,
    group_slug text NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_dsa boolean DEFAULT false NOT NULL
);

ALTER TABLE public.sections OWNER TO postgres;

-- Name: sections sections_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (topic, file);

-- Name: sections_group_slug; Type: INDEX; Schema: public; Owner: postgres

CREATE INDEX sections_group_slug ON public.sections USING btree (group_slug);

-- Name: sections sections_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;

-- Name: sections sections_group_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_group_slug_fkey FOREIGN KEY (group_slug) REFERENCES public.topic_groups(slug) ON DELETE CASCADE;

-- Name: sections; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.sections ENABLE ROW LEVEL SECURITY;

-- Name: sections sections_delete_admin; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY sections_delete_admin ON public.sections FOR DELETE TO authenticated USING (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false));

-- Name: sections sections_delete_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY sections_delete_own ON public.sections FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = created_by));

-- Name: sections sections_insert_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY sections_insert_own ON public.sections FOR INSERT TO authenticated WITH CHECK (((( SELECT auth.uid() AS uid) = created_by) AND (COALESCE(((( SELECT auth.jwt() AS jwt) ->> 'is_anonymous'::text))::boolean, false) = false)));

-- Name: sections sections_select_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY sections_select_own ON public.sections FOR SELECT TO authenticated USING ((created_by = ( SELECT auth.uid() AS uid)));

-- Name: sections sections_update_admin; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY sections_update_admin ON public.sections FOR UPDATE TO authenticated USING (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false)) WITH CHECK (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false));

-- Name: sections sections_update_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY sections_update_own ON public.sections FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = created_by)) WITH CHECK ((( SELECT auth.uid() AS uid) = created_by));

-- Name: TABLE sections; Type: ACL; Schema: public; Owner: postgres

GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.sections TO anon;
GRANT ALL ON TABLE public.sections TO authenticated;
GRANT ALL ON TABLE public.sections TO service_role;

