-- Generated by `npm run db:schema` from the LOCAL Docker DB. Do not edit, do not apply.

-- Name: topic_groups; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE public.topic_groups (
    slug text NOT NULL,
    group_name text NOT NULL,
    blurb text,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_dsa boolean DEFAULT false NOT NULL,
    pinned_at timestamp with time zone
);

ALTER TABLE public.topic_groups OWNER TO postgres;

-- Name: topic_groups topic_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.topic_groups
    ADD CONSTRAINT topic_groups_pkey PRIMARY KEY (slug);

-- Name: topic_groups topic_groups_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres

ALTER TABLE ONLY public.topic_groups
    ADD CONSTRAINT topic_groups_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;

-- Name: topic_groups; Type: ROW SECURITY; Schema: public; Owner: postgres

ALTER TABLE public.topic_groups ENABLE ROW LEVEL SECURITY;

-- Name: topic_groups topic_groups_delete_admin; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY topic_groups_delete_admin ON public.topic_groups FOR DELETE TO authenticated USING (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false));

-- Name: topic_groups topic_groups_delete_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY topic_groups_delete_own ON public.topic_groups FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = created_by));

-- Name: topic_groups topic_groups_insert_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY topic_groups_insert_own ON public.topic_groups FOR INSERT TO authenticated WITH CHECK (((( SELECT auth.uid() AS uid) = created_by) AND (COALESCE(((( SELECT auth.jwt() AS jwt) ->> 'is_anonymous'::text))::boolean, false) = false)));

-- Name: topic_groups topic_groups_select_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY topic_groups_select_own ON public.topic_groups FOR SELECT TO authenticated USING ((created_by = ( SELECT auth.uid() AS uid)));

-- Name: topic_groups topic_groups_update_admin; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY topic_groups_update_admin ON public.topic_groups FOR UPDATE TO authenticated USING (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false)) WITH CHECK (COALESCE((((( SELECT auth.jwt() AS jwt) -> 'app_metadata'::text) ->> 'is_admin'::text))::boolean, false));

-- Name: topic_groups topic_groups_update_own; Type: POLICY; Schema: public; Owner: postgres

CREATE POLICY topic_groups_update_own ON public.topic_groups FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = created_by)) WITH CHECK ((( SELECT auth.uid() AS uid) = created_by));

-- Name: TABLE topic_groups; Type: ACL; Schema: public; Owner: postgres

GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.topic_groups TO anon;
GRANT ALL ON TABLE public.topic_groups TO authenticated;
GRANT ALL ON TABLE public.topic_groups TO service_role;

