#!/bin/sh
# Regenerates supabase/schema/ — one file per table or view, holding the current
# state of the LOCAL Docker DB. A read-only reference for reading the schema;
# supabase/migrations/ stays the source of truth and nothing here is ever applied.
set -e

DB=supabase_db_interview
OUT=supabase/schema

rels=$(docker exec "$DB" psql -U postgres -Atc "
  select c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'v', 'm')
  order by c.relname")

rm -rf "$OUT"
mkdir -p "$OUT"

for rel in $rels; do
  # The dump goes through grep, so $? is the filter's, not pg_dump's, and set -e
  # cannot see a failed dump (and `sh` is not always bash, so no pipefail). A
  # header-only file is the tell: fail loudly rather than commit a snapshot
  # claiming the relation has no columns or policies.
  {
    echo "-- Generated by \`pnpm db:schema\` from the LOCAL Docker DB. Do not edit, do not apply."
    docker exec "$DB" pg_dump -U postgres --schema-only -t "public.$rel" postgres |
      grep -vE '^(SET |SELECT pg_catalog\.set_config|\\restrict|\\unrestrict|--$|-- (PostgreSQL|Dumped))' |
      cat -s
  } > "$OUT/$rel.sql"

  if [ "$(grep -cv '^--' "$OUT/$rel.sql")" -eq 0 ]; then
    echo "db-schema: pg_dump produced nothing for public.$rel" >&2
    exit 1
  fi
done

echo "Wrote $(ls "$OUT" | wc -l | tr -d ' ') files to $OUT/"
